# Generated by Django 3.2.5 on 2021-07-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ruc', models.CharField(max_length=13)),
                ('categoria', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=20)),
                ('horario', models.CharField(max_length=25)),
                ('imagen', models.CharField(max_length=100)),
            ],
        ),
    ]
